language: node_js
node_js:
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
before_install:
  - rvm use 1.9.3
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
  - travis_retry npm install -g grunt-cli@0.1.9
  - travis_retry npm install
notifications:
  email: false
cache:
  bundler: true
  directories:
    - node_modules
branches:
  except:
    - release
